languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "dob"
  email = ""
  image = "img/profile.png"
  headline = "Some kind of Magic."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { x-twitter = "https://twitter.com/" },
    { github = "https://github.com/malasys" },
    { youtube = "https://www.youtube.com/@d0bu_" }
  ]